[book]
title = "The pater Book"
authors = ["Paternoster contributors"]
language = "en"
src = "src"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/paternosterrack/pater"
edit-url-template = "https://github.com/paternosterrack/pater/edit/main/docs/{path}"

[output.html.search]
use-boolean-and = true
